[package]
name = "quantX"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1"
rand = "0.8"
tokio = { version = "1.37", features = ["full"] }
chrono = "0.4"
csv = "1.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }
zip = "0.6"